export const defaultTabs = [
  {
    id: "1",
    title: "Tab 1",
    url: "https://www.google.com/",
    windowId: 1,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "2",
    title: "Tab 2",
    url: "https://www.google.com/",
    windowId: 1,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "3",
    title: "Tab 3",
    url: "https://www.google.com/",
    windowId: 1,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "4",
    title: "Tab 4",
    url: "https://www.google.com/",
    windowId: 1,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "5",
    title: "Tab 5",
    url: "https://www.google.com/",
    windowId: 1,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "6",
    title: "Tab 6",
    url: "https://www.google.com/",
    windowId: 2,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "7",
    title: "Tab 7",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "8",
    title: "Tab 8",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "9",
    title: "Tab 9",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "10",
    title: "Tab 10",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "11",
    title: "Tab 11",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "12",
    title: "Tab 12",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "13",
    title: "Tab 13",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
  {
    id: "14",
    title: "Tab 14",
    url: "https://www.google.com/",
    windowId: 3,
    favIconUrl: "https://www.google.com/favicon.ico",
  },
];
